# Generated by Django 4.2.6 on 2024-05-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommoditiesPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=100)),
                ('preco_de_abertura', models.FloatField()),
                ('maximo_do_dia', models.FloatField()),
                ('minimo_do_dia', models.FloatField()),
                ('preco_de_fechamento', models.FloatField()),
                ('preco_de_fechamento_ajustado', models.FloatField()),
                ('data', models.DateField()),
                ('volume', models.IntegerField()),
                ('codigo', models.CharField(max_length=6)),
                ('moeda', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commodities Price',
                'verbose_name_plural': 'Commodities Prices',
                'ordering': ['ativo', 'data'],
            },
        ),
    ]
