# Generated by Django 4.2.6 on 2024-05-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0002_mediascommodities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediascommodities',
            options={'ordering': ['ativo', 'created_at'], 'verbose_name': 'Media Movel de Commodities', 'verbose_name_plural': 'Medias Moveis de Commodities'},
        ),
        migrations.RemoveField(
            model_name='mediascommodities',
            name='data',
        ),
    ]
