# Generated by Django 4.2.6 on 2024-05-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0003_alter_mediascommodities_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediascommodities',
            old_name='variacai_sem',
            new_name='variacao_sem',
        ),
    ]
