# Generated by Django 4.2.6 on 2024-04-05 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('hora_entrega', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde')], default='Manhã', max_length=255)),
                ('data_entrega', models.DateField()),
                ('vendedor_nome', models.CharField(max_length=255)),
                ('telefone_vendedor', models.CharField(max_length=255)),
                ('vendedor_email', models.CharField(max_length=255)),
                ('forma_pagamento', models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Boleto', 'Boleto')], default='Cartão de Crédito', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True)),
                ('payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Pedido Realizado', 'Pedido Realizado'), ('Pedido Saiu para Entrega', 'Pedido Enviado'), ('Pedido Concluído', 'Pedido Concluído')], default='Pedido Realizado', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.product')),
            ],
        ),
    ]
