# Generated by Django 4.2.6 on 2024-02-24 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data_entrega',
            field=models.DateField(default=datetime.datetime(2024, 2, 24, 15, 53, 40, 435658, tzinfo=datetime.timezone.utc)),
        ),
    ]
