# Generated by Django 4.2.6 on 2024-02-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_data_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data_entrega',
            field=models.DateField(),
        ),
    ]
