# Generated by Django 4.2.6 on 2024-04-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pedido Realizado', 'Pedido Realizado'), ('Pedido Saiu para Entrega', 'Pedido Enviado'), ('Pedido Concluído', 'Pedido Concluído')], default='Pedido Realizado', max_length=50),
        ),
    ]
