# Generated by Django 4.2.6 on 2024-04-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='forma_pagamento',
            field=models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('PIX', 'PIX')], default='Cartão de Crédito', max_length=255),
        ),
    ]
