# Generated by Django 4.2.6 on 2024-04-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hora_entrega',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde')], default='Manhã', max_length=255),
        ),
    ]
